Repository XENONnT/alea, pull requests merged in 2023-07, with the labels that each got.

#37 Removes all hash for parameters not used for each source, and for all…
  alea/blueice_extended_model.py
  alea/examples/unbinned_wimp_statistical_model.yaml
  alea/parameters.py
  alea/statistical_model.py
Labels: enhancement

#32 First implementation of an nT-like likelihood
  .gitignore
  alea/blueice_extended_model.py
  alea/examples/gaussian_model.py
  alea/examples/unbinned_wimp_running.yaml
  alea/examples/unbinned_wimp_statistical_model.yaml
  alea/parameters.py
  alea/simulators.py
  alea/statistical_model.py
  alea/template_source.py
  alea/utils.py
Labels: enhancement

#44 Check if some parameter is not set as guess when fitting
  alea/parameters.py
Labels: inference, make user-friendly

#54 Add first tests module and file indexing system
  alea/__init__.py
  alea/model.py
  alea/model_configs/unbinned_wimp_statistical_model.yaml
  alea/models/__init__.py
  alea/models/blueice_extended_model.py
  alea/parameters.py
  alea/template_source.py
  alea/utils.py
  requirements.txt
  tests/test_blueice_extended_model.py
  tests/test_gaussian_model.py
  tests/test_model.py
  tests/test_parameter.py
  tests/test_statistical_model.py
  tests/test_template_source.py
Labels: testing, robustness

#58 Shape parameters
  .gitignore
  alea/_likelihoods/ll_nt_from_config.py
  alea/model.py
  alea/model_configs/unbinned_wimp_statistical_model.yaml
  alea/models/__init__.py
  alea/models/blueice_extended_model.py
  alea/simulators.py
  alea/template_source.py
  alea/templates/er_template_-1.h5
  alea/templates/er_template_-2.h5
  alea/templates/er_template_0.h5
  alea/templates/er_template_1.h5
  alea/templates/er_template_2.h5
  alea/utils.py
  requirements.txt
  tests/test_blueice_extended_model.py
Labels: enhancement, inference
