Repository XENONnT/alea, pull requests merged in 2023-08, with the labels that each got.

#76 Set best_fit_args to confidence_interval_args if None
  alea/model.py
Labels: inference

#78 Proposal to use pre-commit for continuous integration
  .github/workflows/code_style.yml
  .pre-commit-config.yaml
  README.md
  alea/__init__.py
  alea/examples/gaussian_model.py
  alea/model.py
  alea/models/blueice_extended_model.py
  alea/parameters.py
  alea/runner.py
  alea/simulators.py
  alea/template_source.py
  alea/utils.py
  docs/requirements-docs.txt
  docs/source/build_release_notes.py
  docs/source/conf.py
  notebooks/gaussian_model.ipynb
  setup.cfg
  setup.py
  tests/conftest.py
  tests/test_blueice_extended_model.py
  tests/test_gaussian_model.py
  tests/test_model.py
  tests/test_parameter.py
  tests/test_runner.py
  tests/test_template_source.py
Labels: testing, make user-friendly

#75 Example notebooks
  README.md
  alea/examples/configs/unbinned_wimp_running.yaml
  alea/examples/configs/unbinned_wimp_statistical_model.yaml
  alea/examples/configs/unbinned_wimp_statistical_model_simple.yaml
  alea/examples/templates/er_template_-1.h5
  alea/examples/templates/er_template_-2.h5
  alea/examples/templates/er_template_1.h5
  alea/examples/templates/er_template_2.h5
  alea/models/blueice_extended_model.py
  alea/parameters.py
  alea/runner.py
  docs/source/index.rst
  docs/source/installation.rst
  docs/source/notebooks/0_introduction.ipynb
  docs/source/notebooks/1_rate_and_shape.ipynb
  docs/source/notebooks/2_fitting_and_ci.ipynb
  docs/source/notebooks/3_sensitivity.ipynb
  docs/source/notebooks/gaussian_model.ipynb
  notebooks/0_introduction.ipynb
  notebooks/1_rate_and_shape.ipynb
  notebooks/2_fitting_and_ci.ipynb
  notebooks/3_sensitivity.ipynb
  notebooks/gaussian_model.ipynb
  tests/test_blueice_extended_model.py
  tests/test_runner.py
Labels: make user-friendly
